// ─────────────────────────────────────────────────────────────
//  MNETI — ZK Proof Generator
//  File: sdk/src/zk/proof_generator.ts
//
//  PURPOSE:
//  Generates ZK proofs locally on the user's device.
//  Private data (M-Pesa history, identity info) NEVER leaves
//  the device. Only the proof and public signals go on-chain.
//
//  USAGE:
//  import { generateKycProof, generateCreditProof } from './proof_generator';
//
//  const { proof, publicSignals } = await generateKycProof({
//    fullName: "John Doe",
//    idNumber: "12345678",
//    phone: "+254712345678",
//    sanctionsClear: true,
//    jurisdictionCode: 254,
//    kycExpiry: 1800000000,
//    tier: 0,
//    walletPubkey: wallet.publicKey,
//  });
// ─────────────────────────────────────────────────────────────

import { PublicKey } from "@solana/web3.js";
import * as snarkjs  from "snarkjs";
import * as crypto   from "crypto";
import path          from "path";

// ── PATHS TO CIRCUIT ARTIFACTS ────────────────────────────────
// These are generated by: bash circuits/scripts/build_all.sh
const CIRCUITS_DIR = path.join(__dirname, "../../../circuits");

const KYC_WASM  = path.join(CIRCUITS_DIR, "kyc-compliance/build/kyc-compliance_js/kyc-compliance.wasm");
const KYC_ZKEY  = path.join(CIRCUITS_DIR, "kyc-compliance/keys/kyc-compliance_final.zkey");
const KYC_VKEY  = path.join(CIRCUITS_DIR, "kyc-compliance/keys/kyc-compliance_verification_key.json");

const CREDIT_WASM = path.join(CIRCUITS_DIR, "credit-score/build/credit-score_js/credit-score.wasm");
const CREDIT_ZKEY = path.join(CIRCUITS_DIR, "credit-score/keys/credit-score_final.zkey");
const CREDIT_VKEY = path.join(CIRCUITS_DIR, "credit-score/keys/credit-score_verification_key.json");

// ── TYPES ─────────────────────────────────────────────────────

export interface KycProofInput {
  fullName:         string;
  idNumber:         string;
  phone:            string;
  sanctionsClear:   boolean;
  jurisdictionCode: number;
  kycExpiry:        number;
  tier:             0 | 1 | 2;
  walletPubkey:     PublicKey;
}

export interface CreditProofInput {
  monthlyIncomes:    number[];  // 24 months KES in raw units
  monthlyExpenses:   number[];  // 24 months
  paymentSuccesses:  number[];  // 24 months
  paymentFailures:   number[];  // 24 months
  monthlySavings:    number[];  // 24 months
  walletPubkey:      PublicKey;
}

export interface ZkProofResult {
  proof: {
    a: Uint8Array;   // 64 bytes
    b: Uint8Array;   // 128 bytes
    c: Uint8Array;   // 64 bytes
  };
  publicSignals: Record<string, any>;
}

// ── HELPERS ───────────────────────────────────────────────────

/// Hash a string to a field element using SHA256
function hashToField(input: string): bigint {
  const hash = crypto.createHash("sha256").update(input).digest("hex");
  return BigInt("0x" + hash) % BigInt("21888242871839275222246405745257275088548364400416034343698204186575808495617");
}

/// Convert a Solana public key to a field element
function pubkeyToField(pubkey: PublicKey): bigint {
  const bytes = pubkey.toBytes();
  const hex   = Buffer.from(bytes).toString("hex");
  return BigInt("0x" + hex) % BigInt("21888242871839275222246405745257275088548364400416034343698204186575808495617");
}

/// Convert snarkjs proof points to Uint8Array format for Solana
function proofToBytes(proof: any): { a: Uint8Array; b: Uint8Array; c: Uint8Array } {
  const hexToBytes = (hex: string) => {
    const h   = hex.startsWith("0x") ? hex.slice(2) : hex;
    const padded = h.padStart(64, "0");
    return Buffer.from(padded, "hex");
  };

  const pointToBytes = (point: string[]): Uint8Array => {
    return Buffer.concat([hexToBytes(point[0]), hexToBytes(point[1])]);
  };

  const g2ToBytes = (point: string[][]): Uint8Array => {
    return Buffer.concat([
      hexToBytes(point[0][0]), hexToBytes(point[0][1]),
      hexToBytes(point[1][0]), hexToBytes(point[1][1]),
    ]);
  };

  return {
    a: pointToBytes(proof.pi_a),
    b: g2ToBytes(proof.pi_b),
    c: pointToBytes(proof.pi_c),
  };
}

// ── KYC PROOF GENERATOR ───────────────────────────────────────

export async function generateKycProof(
  input: KycProofInput
): Promise<ZkProofResult> {
  const nonce = BigInt(Math.floor(Math.random() * 1e15));
  const now   = Math.floor(Date.now() / 1000);

  // Hash private data — this is the ONLY processing of PII
  const circuitInput = {
    fullNameHash:     hashToField(input.fullName).toString(),
    idNumberHash:     hashToField(input.idNumber).toString(),
    phoneHash:        hashToField(input.phone).toString(),
    sanctionsResult:  input.sanctionsClear ? "0" : "1",
    jurisdictionCode: input.jurisdictionCode.toString(),
    kycExpiry:        input.kycExpiry.toString(),
    currentTime:      now.toString(),
    tierLevel:        input.tier.toString(),
    nonce:            nonce.toString(),
    walletPubkey:     pubkeyToField(input.walletPubkey).toString(),
  };

  console.log("[MNETI-ZK] Generating KYC proof locally...");
  console.log("[MNETI-ZK] Private data stays on device — only proof goes on-chain");

  // Generate proof using snarkjs (runs locally, no network)
  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    circuitInput,
    KYC_WASM,
    KYC_ZKEY
  );

  // Verify locally before submitting
  const vKey   = require(KYC_VKEY);
  const isValid = await snarkjs.groth16.verify(vKey, publicSignals, proof);
  if (!isValid) {
    throw new Error("KYC proof verification failed locally");
  }

  console.log("[MNETI-ZK] ✅ KYC proof generated and verified locally");

  return {
    proof: proofToBytes(proof),
    publicSignals: {
      complianceTier:  parseInt(publicSignals[0]),
      jurisdictionOk:  publicSignals[1] === "1",
      notSanctioned:   publicSignals[2] === "1",
      kycValidUntil:   parseInt(publicSignals[3]),
      commitment:      hexToBytes32(publicSignals[4]),
      identityHash:    hexToBytes32(publicSignals[5]),
    },
  };
}

// ── CREDIT SCORE PROOF GENERATOR ──────────────────────────────

export async function generateCreditProof(
  input: CreditProofInput
): Promise<ZkProofResult> {
  const nonce = BigInt(Math.floor(Math.random() * 1e15));

  // Pad arrays to 24 months if shorter
  const pad = (arr: number[], len: number) =>
    [...arr, ...Array(len - arr.length).fill(0)].slice(0, len);

  const circuitInput = {
    monthlyIncomes:    pad(input.monthlyIncomes, 24).map(String),
    monthlyExpenses:   pad(input.monthlyExpenses, 24).map(String),
    paymentSuccesses:  pad(input.paymentSuccesses, 24).map(String),
    paymentFailures:   pad(input.paymentFailures, 24).map(String),
    monthlySavings:    pad(input.monthlySavings, 24).map(String),
    walletPubkey:      pubkeyToField(input.walletPubkey).toString(),
    nonce:             nonce.toString(),
  };

  console.log("[MNETI-ZK] Generating credit score proof locally...");
  console.log("[MNETI-ZK] M-Pesa history stays on device — only score goes on-chain");

  const { proof, publicSignals } = await snarkjs.groth16.fullProve(
    circuitInput,
    CREDIT_WASM,
    CREDIT_ZKEY
  );

  const vKey    = require(CREDIT_VKEY);
  const isValid = await snarkjs.groth16.verify(vKey, publicSignals, proof);
  if (!isValid) {
    throw new Error("Credit proof verification failed locally");
  }

  console.log("[MNETI-ZK] ✅ Credit proof generated. Score:", publicSignals[0]);

  return {
    proof: proofToBytes(proof),
    publicSignals: {
      creditScore:        parseInt(publicSignals[0]),
      incomeBand:         parseInt(publicSignals[1]),
      paymentReliability: parseInt(publicSignals[2]),
      savingsRateBand:    parseInt(publicSignals[3]),
      monthsOfHistory:    parseInt(publicSignals[4]),
      commitment:         hexToBytes32(publicSignals[5]),
    },
  };
}

// ── HELPER: Convert field element to 32-byte array ────────────
function hexToBytes32(value: string): Uint8Array {
  const hex    = BigInt(value).toString(16).padStart(64, "0");
  return Buffer.from(hex, "hex");
}
