[toolchain]
anchor_version = "0.31.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
mneti_rbac           = "33qcPinr2tuap9Yfj9xK8rmosps28wDUzVwntr3bhFEg"
mneti_vault_registry = "C8nAsftZ6RwaRsHu4TBZTgXvHMixTvzz1rLJzqsn5euF"
mneti_kesh           = "7mRxU93YaGs9QaEhA2tXTpep4TCQ95LD7rDz5E4567of"

[programs.devnet]
mneti_rbac           = "33qcPinr2tuap9Yfj9xK8rmosps28wDUzVwntr3bhFEg"
mneti_vault_registry = "C8nAsftZ6RwaRsHu4TBZTgXvHMixTvzz1rLJzqsn5euF"
mneti_kesh           = "7mRxU93YaGs9QaEhA2tXTpep4TCQ95LD7rDz5E4567of"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet  = "~/.config/solana/id.json"
