[workspace]
members = [
    "programs/mneti-rbac",
    "programs/mneti-vault-registry",
    "programs/mneti-kesh",
    "programs/mneti-oracle",
    "programs/mneti-compliance",
    "programs/mneti-vault",
    "programs/mneti-payments",
    "programs/mneti-travel-rule",
    "programs/mneti-remittance",

]
resolver = "2"

[profile.release]
overflow-checks = true
lto             = "fat"
codegen-units   = 1


[profile.release.build-override]
opt-level     = 3
incremental   = false
codegen-units = 1


